### ISSUE TITLE
cmd-shift-a to change api keys - no window popping up

### ISSUE THREAD

**Issue by philoushka** [voxmedia/Transcriber#2]
`cmd-shift-a` only produces a boop sound in Mac OS X El Cap.

I couldn't find the `wttskeys.json` file either.

If I want to make my own json file, what content should be in that file?

**Comment by pietrop** [comment]
Apologies for late reply, only so this now, what do you mean by "I want to make my own json file"?

This app was an initial prototype to test the quality of IBM STT, I am now working on a more full fledge version http://www.autoedit.io - https://github.com/OpenNewsLabs/autoEdit_2

**Comment by pietrop** [comment]
ah, sorry my bad now I see what you meant, this is what the json file for `wttskeys.json` would look like. 

```json
{"password": "IBM STT SERVICE PASSWORD","username": "IBM STT SERVICE USERNAME", "type": "dev"}
```

I noticed you closed the issue, but I just realised now what you where asking.
Hope this helps
